### ISSUE TITLE
Feature request: `analyze_block` should return the wallet transactions

### ISSUE THREAD

**Issue by ismaelsadeeq** [ishaanam/wallet-fingerprinting#1]
I find this wallet-fingerprinting tool extremely useful in my work related to fee estimation. 
I am currently trying to understand the utilization of Bitcoin Core's fee estimation in the network. 

Currently analyze block only return the number of transaction for each wallet it detect.
It would be highly beneficial if the `analyze_block` function or another similar utility could provide the transactions for each wallet it successfully detects. 
My particular interest lies in Bitcoin Core, but the ability to retrieve data for other wallets would also be very useful.

**Comment by ismaelsadeeq** [comment]
Cc @ishaanam 
Locally, I've created analyze_block_with_detail, which does exactly that. If you believe this would be useful, I'd be happy to create a PR for it

**Comment by ishaanam** [comment]
@ismaelsadeeq thanks for taking a look at this! Returning the transactions seems useful, if you opened a PR implementing this I would be happy to take a look at it. One note is that instead of creating a new function, perhaps it would be better to add a `verbose` option to the existing `analyze_block` function?

**Comment by ismaelsadeeq** [comment]
Opened #2 with your suggestion.
